name: inditrans
description: An experimental transliterator library for some Indic scripts.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.11.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  js: ^0.6.5
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^6.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.hello
        ffiPlugin: true
      ios:
        pluginClass: HelloPlugin
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
