// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `python3 tool/generate_bindings.py`.
// Uses universal_ffi so the same public bindings work on native and web.
// ignore_for_file: type=lint, unused_import
import 'package:universal_ffi/ffi.dart' as ffi;

/// Bindings for `inditrans`.
///
/// Regenerate from `native/src/exports.h` with `python3 tool/generate_bindings.py`.
class InditransBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  InditransBindings(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  InditransBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Transliterates null-terminated UTF-8 text from source script to target script.
  ///
  /// Allocates a new null-terminated C string on the heap containing the transliterated result.
  /// The caller assumes ownership of the returned pointer and MUST release it using releaseBuffer().
  ///
  /// @param text The null-terminated UTF-8 input string.
  /// @param from Source script identifier or alias (e.g. "itrans", "devanagari").
  /// @param to Target script identifier or alias (e.g. "bengali", "iast").
  /// @param options Bitwise combination of TranslitOptions flags.
  /// @param skipStart Delimiter marking the start of protected text blocks (e.g. "##").
  /// @param skipEnd Delimiter marking the end of protected text blocks (e.g. "##").
  /// @return Pointer to heap-allocated result string, or nullptr on failure.
  ffi.Pointer<ffi.Uint8> transliterate(
    ffi.Pointer<ffi.Uint8> text,
    ffi.Pointer<ffi.Uint8> from,
    ffi.Pointer<ffi.Uint8> to,
    int options,
    ffi.Pointer<ffi.Uint8> skipStart,
    ffi.Pointer<ffi.Uint8> skipEnd,
  ) {
    return _transliterate(text, from, to, options, skipStart, skipEnd);
  }

  late final _transliteratePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Uint8> Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Pointer<ffi.Uint8>,
            ffi.UnsignedLong,
            ffi.Pointer<ffi.Uint8>,
            ffi.Pointer<ffi.Uint8>,
          )
        >
      >(
        'transliterate',
      );
  late final _transliterate = _transliteratePtr
      .asFunction<ffi.Pointer<ffi.Uint8> Function(
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>
        )>();

  /// Checks whether a script identifier or alias is physically supported by the engine.
  ///
  /// Note: Virtual sources such as "indic" are handled dynamically by wrapper layers;
  /// this function returns non-zero only if a concrete script dictionary exists for the name.
  ///
  /// @param script The script identifier or alias to query (case-insensitive).
  /// @return Non-zero (1) if supported, 0 otherwise.
  int isScriptSupported(
    ffi.Pointer<ffi.Uint8> script,
  ) {
    return _isScriptSupported(script);
  }

  late final _isScriptSupportedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(
            ffi.Pointer<ffi.Uint8>
          )>>(
        'isScriptSupported',
      );
  late final _isScriptSupported = _isScriptSupportedPtr
      .asFunction<int Function(
          ffi.Pointer<ffi.Uint8>
        )>();

  /// Deallocates memory previously allocated by transliterate().
  ///
  /// Must be called across the FFI/ABI boundary for every non-null buffer returned by transliterate().
  ///
  /// @param buffer Pointer to heap buffer to free (safe to pass nullptr).
  void releaseBuffer(
    ffi.Pointer<ffi.Uint8> buffer,
  ) {
    return _releaseBuffer(buffer);
  }

  late final _releaseBufferPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(
            ffi.Pointer<ffi.Uint8>
          )>>(
        'releaseBuffer',
      );
  late final _releaseBuffer = _releaseBufferPtr
      .asFunction<void Function(
          ffi.Pointer<ffi.Uint8>
        )>();
}
