export enum Script {
  assamese = 'assamese',
  bengali = 'bengali',
  devanagari = 'devanagari',
  readablelatin = 'readablelatin',
  gujarati = 'gujarati',
  gurmukhi = 'gurmukhi',
  iast = 'iast',
  indic = 'indic',
  ipa = 'ipa',
  iso = 'iso',
  itrans = 'itrans',
  kannada = 'kannada',
  malayalam = 'malayalam',
  oriya = 'oriya',
  sinhala = 'sinhala',
  tamil = 'tamil',
  telugu = 'telugu',
}
