// GENERATED CODE - DO NOT MODIFY BY HAND

/// Supported scripts
export enum Script {
  assamese = 'assamese',
  bangla = 'bangla',
  bengali = 'bengali',
  burmese = 'burmese',
  devanagari = 'devanagari',
  gujarati = 'gujarati',
  gurmukhi = 'gurmukhi',
  hindi = 'hindi',
  iast = 'iast',
  indic = 'indic',
  ipa = 'ipa',
  iso = 'iso',
  itrans = 'itrans',
  kannada = 'kannada',
  khmer = 'khmer',
  malayalam = 'malayalam',
  odia = 'odia',
  oriya = 'oriya',
  punjabi = 'punjabi',
  readableLatin = 'readableLatin',
  sanskrit = 'sanskrit',
  sinhala = 'sinhala',
  tamil = 'tamil',
  tamilExtended = 'tamilExtended',
  telugu = 'telugu',
  thai = 'thai',
  tibetan = 'tibetan',
  titus = 'titus',
  wx = 'wx',
}
