name: sweph
description: Cross-platform bindings of Swiss Ephemeris APIs for Flutter/Dart.
version: 2.10.03+6
homepage: https://github.com/vm75/sweph.dart
repository: https://github.com/vm75/sweph.dart

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.11.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^6.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
  assets:
    - native/sweph/src/ast_list.txt
    - native/sweph/src/sefstars.txt
    - native/sweph/src/seleapsec.txt
