name: inditrans
description: A functional transliterator library for the most common Indic/Brahmic scripts.
version: 0.9.0
repository: https://github.com/vm75/inditrans/

environment:
  sdk: ^3.5.1
  flutter: ">=2.11.0"

dependencies:
  universal_ffi: ^1.0.6

dev_dependencies:
  ffigen: 13.0.0
  lints: ^4.0.0
  test: ^1.24.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web:
  assets:
    - assets/
