name: inditrans
description: An experimental transliterator library for some Indic scripts.
version: 0.1.8
repository: https://github.com/vm75/inditrans/

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  html: ^0.15.1
  inject_js: ^2.0.0
  js: ^0.6.5
  plugin_platform_interface: ^2.0.2
  wasm_interop: ^2.0.1
  wasm_ffi: ^0.9.3

dev_dependencies:
  ffigen: ^6.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web:
  assets:
    - assets/
