#!/usr/bin/env python3
"""Generate the small Dart FFI binding class from ``native/src/exports.h``.

The C ABI deliberately exposes only three functions and four C types. A small
checked renderer is easier to audit than a general C parser and removes the
ffigen/Dart dependency from repository maintenance tools. Extend the type map
and add fixtures before expanding the exported ABI.
"""

from pathlib import Path
import re
import sys


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
HEADER = REPOSITORY_ROOT / "native/src/exports.h"
OUTPUT = REPOSITORY_ROOT / "flutter/lib/src/bindings.dart"

TYPE_MAP = {
    "char*": ("ffi.Pointer<ffi.Uint8>", "ffi.Pointer<ffi.Uint8>"),
    "int": ("ffi.Int", "int"),
    "void": ("ffi.Void", "void"),
    "unsigned long": ("ffi.UnsignedLong", "int"),
}


def parse_exports(header: str) -> list[dict]:
    """Read documented ext_def declarations and reject unsupported C types."""
    pattern = re.compile(
        r"(?P<comment>(?:^[ \t]*///[^\n]*\n)+)[ \t]*ext_def\(\s*"
        r"(?P<return>[^)]+)\)\s+(?P<name>\w+)\((?P<args>.*?)\);",
        re.MULTILINE | re.DOTALL,
    )
    functions = []
    for match in pattern.finditer(header):
        returns = " ".join(match.group("return").split())
        if returns not in TYPE_MAP:
            raise ValueError(f"Unsupported exported return type: {returns}")
        args = []
        for declaration in filter(None, (x.strip() for x in match.group("args").split(","))):
            arg_match = re.fullmatch(r"(const\s+)?(.+?)\s+(\w+)", declaration)
            if not arg_match:
                raise ValueError(f"Cannot parse exported argument: {declaration}")
            c_type = " ".join(arg_match.group(2).split())
            if arg_match.group(1):
                c_type += " const"
            # Const applies to the pointee here and does not change FFI shape.
            c_type = c_type.removesuffix(" const")
            if c_type not in TYPE_MAP or c_type == "void":
                raise ValueError(f"Unsupported exported argument type: {c_type}")
            args.append({"name": arg_match.group(3), "c_type": c_type,
                         "native": TYPE_MAP[c_type][0], "dart": TYPE_MAP[c_type][1]})
        functions.append({"comment": "\n".join(line.strip()[4:] for line in match.group("comment").splitlines()),
                          "name": match.group("name"), "c_type": returns,
                          "native": TYPE_MAP[returns][0], "dart": TYPE_MAP[returns][1], "args": args})
    if not functions:
        raise ValueError(f"No ext_def exports found in {HEADER}")
    return functions


def render(functions: list[dict]) -> str:
    """Render lookup wrappers and native signatures from the parsed C ABI."""
    lines = [
        "// ignore_for_file: always_specify_types",
        "// ignore_for_file: camel_case_types",
        "// ignore_for_file: constant_identifier_names",
        "// ignore_for_file: non_constant_identifier_names",
        "",
        "// AUTO GENERATED FILE, DO NOT EDIT.",
        "//",
        "// Generated by `python3 tool/generate_bindings.py`.",
        "// Uses universal_ffi so the same public bindings work on native and web.",
        "// ignore_for_file: type=lint, unused_import",
        "import 'package:universal_ffi/ffi.dart' as ffi;",
        "",
        "/// Bindings for `inditrans`.",
        "///",
        "/// Regenerate from `native/src/exports.h` with `python3 tool/generate_bindings.py`.",
        "class InditransBindings {",
        "  /// Holds the symbol lookup function.",
        "  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;",
        "",
        "  /// The symbols are looked up in [dynamicLibrary].",
        "  InditransBindings(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;",
        "",
        "  /// The symbols are looked up with [lookup].",
        "  InditransBindings.fromLookup(",
        "    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,",
        "  ) : _lookup = lookup;",
    ]

    for function in functions:
        args = function["args"]
        lines += ["", f"  /// {function['comment']}", f"  {function['dart']} {function['name']}("]
        lines.extend(f"    {arg['dart']} {arg['name']}," for arg in args)
        lines += ["  ) {", f"    return _{function['name']}({', '.join(arg['name'] for arg in args)});", "  }"]

        native_args = ",\n".join(f"            {arg['native']}" for arg in args)
        dart_args = ",\n".join(f"          {arg['dart']}" for arg in args)
        native_function = (f"{function['native']} Function(\n{native_args}\n          )" if args
                           else f"{function['native']} Function()")
        dart_function = (f"{function['dart']} Function(\n{dart_args}\n        )" if args
                         else f"{function['dart']} Function()")
        if len(args) == 1:
            lookup_type = f"ffi.NativeFunction<{native_function}>"
            lines += ["", f"  late final _{function['name']}Ptr =", f"      _lookup<{lookup_type}>(",
                      f"        '{function['name']}',", "      );"]
        else:
            lines += ["", f"  late final _{function['name']}Ptr =", "      _lookup<",
                      "        ffi.NativeFunction<", f"          {function['native']} Function("]
            lines.extend(f"            {arg['native']}," for arg in args)
            lines += ["          )", "        >", "      >(", f"        '{function['name']}',", "      );"]
        lines += [f"  late final _{function['name']} = _{function['name']}Ptr",
                  f"      .asFunction<{dart_function}>();"]
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    if not (REPOSITORY_ROOT / "flutter/pubspec.yaml").is_file():
        print("Could not locate the repository root from this script", file=sys.stderr)
        return 1
    OUTPUT.write_text(render(parse_exports(HEADER.read_text(encoding="utf-8"))), encoding="utf-8")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError) as error:
        print(f"generate_bindings: {error}", file=sys.stderr)
        raise SystemExit(1)
