name: example_dart
description: Vanilla Dart example for sweph
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.10.8

dependencies:
  inditrans:
    path: ../
  ffi: ^2.1.5
  web: ^1.1.1
  http: ^1.6.0

dev_dependencies:
  build_runner: ^2.11.0
  build_web_compilers: ^4.4.10
  ffigen: ^20.1.1
  lints: ^6.1.0
