name: example_dart
description: Vanilla Dart example for sweph
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  ffi: ^2.1.3
  web: ^1.0.0
  inditrans:
    path: ../
  http: ^1.2.2

dev_dependencies:
  build_runner: ^2.4.12
  build_web_compilers: ^4.0.11
  ffigen: ^14.0.0
  lints: ^4.0.0
